### ISSUE TITLE
Logining in with session every time we submit a problem

### ISSUE THREAD

**Issue by rohanailoni** [mdbrnowski/codeforces-toolbox#15]
As i have seen the code we are login in every time we submit a solution.At the time of the contest there is high traffic and we are pinging 2 times . waititng till we get `accepted` or `wrong answer`(every 0.05 sec sleep).

My idea is to create a `cft login` which will login and store the pickle the session object in `~/.codeforces-toolbox` folder so while submitting we can open the pickle object and send the submit solution

**Comment by mdbrnowski** [comment]
I agree this is a good idea and I was going to look into it in the future. However, I do not believe that the introduction of a new command is needed. It would be better to solve it as it normally is in the browser -- cookies are responsible for logging in. If they expire, the site sends a login request.

**Comment by mdbrnowski** [comment]
If you want to take care of it, say so and I'll assign you.

**Comment by rohanailoni** [comment]
@mdbrnowski  yes i will give it a try

**Comment by mdbrnowski** [comment]
Closed with #16
